#!/bin/bash

rm -rf dist/firefox
./deploy firefox

cd $FIREFOX_ADDON_DIR
source bin/activate
cd -

cd dist/firefox

if [ "$1" == "mobile" ]
then
	shift	# remove "mobile" from args
	args="-a fennec-on-device -b `which adb` --mobile-app firefox --force-mobile"
fi
args="$args $*"

cfx run $args
#cfx run -b /usr/local/firefox-30/firefox
