#!/bin/bash

# usage:
#   ./run-firefox
#   ./run-firefox -b /<path-to-old-firefox>/firefox
#	./run-firefox mobile
#	./run-firefox xpi
#
# min supported version (due to use of jpm):
#  desktop: 38
#  android: 38


rm -rf dist/firefox
./deploy legacy

cd dist/firefox

if [ "$1" == "xpi" ]
then
	jpm xpi
	mv *.xpi ../../location-guard.xpi

else
	if [ "$1" == "mobile" ]
	then
		shift	# remove "mobile" from $*

		# default is -b fennec
		#
		jpm-mobile run -v --adb `which adb` -b firefox $*	||
			printf "\n\nif you get error 'cmd is not defined' install patched version:\n\nsudo npm install -g ncalexan/jpm-mobile#fixes\n\n"
	else
		# jpm doesn't detect firefox on Ubuntu so we pass -b (which will be overriden if -b is also given in $*)
		#
		jpm run --binary-args -jsconsole -b `which firefox` $*
	fi

fi
