#!/bin/bash

# usage:
#   ./run-firefox
#   ./run-firefox -b /<path-to-old-firefox>/firefox6
#	./run-firefox mobile
#	./run-firefox xpi
#
# min supported version:
#  desktop: 31
#  android: 34


rm -rf dist/firefox
./deploy firefox

cd $FIREFOX_ADDON_DIR
source bin/activate
cd -

cd dist/firefox

if [ "$1" == "xpi" ]
then
	cfx xpi --force-mobile
	mv location-guard.xpi ../../

else
	if [ "$1" == "mobile" ]
	then
		shift	# remove "mobile" from $*
		args="-a fennec-on-device -b `which adb` --mobile-app firefox --force-mobile"
	fi

	cfx run --binary-args -jsconsole $args $*
fi
